version: "3.8"

services:
  db:
    restart: always
    image: postgres:12.10
    expose:
      - "${PG_PORT}"
    ports:
      - "${PG_PORT}:5432"
    networks:
      - backend
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DATABASE}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  fastapi:
    build: .
    command:
      ["uvicorn", "${FILE_TO_RUN}:app", "--host", "0.0.0.0", "--port", "8000"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    restart: always
    tty: true
    stdin_open: true
    networks:
      - backend
    depends_on:
      - db

volumes:
  db_data:

networks:
  backend:
    driver: bridge
